import { Album, WishlistItem } from "./types"

export const INITIAL_ALBUMS: Album[] = [
  { id: 'a1', title: 'Rumours', artist: 'Fleetwood Mac', year: 1977, genre: 'Rock', format: 'vinyl', condition: 'Near Mint', rating: 5, purchasePrice: 28, purchaseDate: '2023-06-10', notes: 'Picked up at a flea market. Original pressing!', tracks: ['Second Hand News', 'Dreams', 'Never Going Back Again', 'The Chain', 'You Make Loving Fun', 'I Don\'t Want to Know', 'Oh Daddy', 'Gold Dust Woman'], color: '#E87575', addedDate: '2023-06-10' },
  { id: 'a2', title: 'Kind of Blue', artist: 'Miles Davis', year: 1959, genre: 'Jazz', format: 'vinyl', condition: 'Very Good+', rating: 5, purchasePrice: 45, purchaseDate: '2023-03-22', notes: 'Reissue, sounds incredible.', tracks: ['So What', 'Freddie Freeloader', 'Blue in Green', 'All Blues', 'Flamenco Sketches'], color: '#A69BC8', addedDate: '2023-03-22' },
  { id: 'a3', title: 'OK Computer', artist: 'Radiohead', year: 1997, genre: 'Alternative', format: 'cd', condition: 'Near Mint', rating: 5, purchasePrice: 12, purchaseDate: '2022-11-05', notes: 'Original CD with booklet in perfect shape.', tracks: ['Airbag', 'Paranoid Android', 'Subterranean Homesick Alien', 'Exit Music', 'Let Down', 'Karma Police', 'Fitter Happier', 'Electioneering', 'Climbing Up the Walls', 'No Surprises', 'Lucky', 'The Tourist'], color: '#91C9AD', addedDate: '2022-11-05' },
  { id: 'a4', title: 'Blue', artist: 'Joni Mitchell', year: 1971, genre: 'Folk', format: 'vinyl', condition: 'Very Good', rating: 4, purchasePrice: 22, purchaseDate: '2023-08-14', notes: 'A few surface scratches but plays clean.', tracks: ['All I Want', 'My Old Man', 'Little Green', 'Carey', 'Blue', 'California', 'This Flight Tonight', 'River', 'A Case of You', 'The Last Time I Saw Richard'], color: '#F2C66D', addedDate: '2023-08-14' },
  { id: 'a5', title: 'Purple Rain', artist: 'Prince', year: 1984, genre: 'Funk', format: 'vinyl', condition: 'Very Good+', rating: 5, purchasePrice: 18, purchaseDate: '2023-01-30', notes: '', tracks: ['Let\'s Go Crazy', 'Take Me With U', 'The Beautiful Ones', 'Computer Blue', 'Darling Nikki', 'When Doves Cry', 'I Would Die 4 U', 'Baby I\'m A Star', 'Purple Rain'], color: '#7B68EE', addedDate: '2023-01-30' },
  { id: 'a6', title: 'Nevermind', artist: 'Nirvana', year: 1991, genre: 'Grunge', format: 'cd', condition: 'Good', rating: 4, purchasePrice: 8, purchaseDate: '2021-07-19', notes: 'Case cracked but disc is fine.', tracks: ['Smells Like Teen Spirit', 'In Bloom', 'Come as You Are', 'Breed', 'Lithium', 'Polly', 'Territorial Pissings', 'Drain You', 'Lounge Act', 'Stay Away', 'On a Plain', 'Something in the Way'], color: '#F4A987', addedDate: '2021-07-19' },
  { id: 'a7', title: 'The Miseducation of Lauryn Hill', artist: 'Lauryn Hill', year: 1998, genre: 'R&B', format: 'cassette', condition: 'Very Good', rating: 4, purchasePrice: 5, purchaseDate: '2022-04-02', notes: 'Found in a thrift store bin. Sounds great!', tracks: ['Intro', 'Lost Ones', 'Ex-Factor', 'To Zion', 'Doo Wop (That Thing)', 'Superstar', 'Final Hour', 'When It Hurts So Bad', 'I Used to Love Him', 'Forgive Them Father'], color: '#91C9AD', addedDate: '2022-04-02' },
  { id: 'a8', title: 'Illmatic', artist: 'Nas', year: 1994, genre: 'Hip-Hop', format: 'cd', condition: 'Near Mint', rating: 5, purchasePrice: 15, purchaseDate: '2023-09-01', notes: 'Classic. Perfect condition.', tracks: ['The Genesis', 'N.Y. State of Mind', 'Dead Presidents', 'Halftime', 'The World Is Yours', 'Memory Lane', 'One Love', 'One Time 4 Your Mind', 'Lucky Me'], color: '#E87575', addedDate: '2023-09-01' },
  { id: 'a9', title: 'Discovery', artist: 'Daft Punk', year: 2001, genre: 'Electronic', format: 'vinyl', condition: 'Mint', rating: 5, purchasePrice: 55, purchaseDate: '2023-10-15', notes: 'Sealed repress. Stunning.', tracks: ['One More Time', 'Aerodynamic', 'Digital Love', 'Harder Better Faster Stronger', 'Crescendolls', 'Nightvision', 'Superheroes', 'High Life', 'Something About Us', 'Voyager', 'Veridis Quo', 'Short Circuit', 'Face to Face', 'Too Long'], color: '#F2C66D', addedDate: '2023-10-15' },
  { id: 'a10', title: 'Tapestry', artist: 'Carole King', year: 1971, genre: 'Pop', format: 'vinyl', condition: 'Very Good', rating: 4, purchasePrice: 16, purchaseDate: '2022-09-08', notes: '', tracks: ['I Feel the Earth Move', 'So Far Away', 'It\'s Too Late', 'Home Again', 'Beautiful', 'Way Over Yonder', 'You\'ve Got a Friend', 'Where You Lead', 'Will You Love Me Tomorrow', 'Smackwater Jack', 'Tapestry', '(You Make Me Feel Like) A Natural Woman'], color: '#A69BC8', addedDate: '2022-09-08' },
  { id: 'a11', title: 'Thriller', artist: 'Michael Jackson', year: 1982, genre: 'Pop', format: 'vinyl', condition: 'Very Good+', rating: 5, purchasePrice: 20, purchaseDate: '2022-12-25', notes: 'Christmas gift to myself.', tracks: ['Wanna Be Startin\' Somethin\'', 'Baby Be Mine', 'The Girl Is Mine', 'Thriller', 'Beat It', 'Billie Jean', 'Human Nature', 'P.Y.T.', 'The Lady in My Life'], color: '#F4A987', addedDate: '2022-12-25' },
  { id: 'a12', title: 'Born to Run', artist: 'Bruce Springsteen', year: 1975, genre: 'Rock', format: 'cd', condition: 'Good', rating: 3, purchasePrice: 6, purchaseDate: '2021-02-14', notes: '', tracks: ['Thunder Road', 'Tenth Avenue Freeze-Out', 'Night', 'Backstreets', 'Born to Run', 'She\'s the One', 'Meeting Across the River', 'Jungleland'], color: '#91C9AD', addedDate: '2021-02-14' },
]

export const INITIAL_WISHLIST: WishlistItem[] = [
  { id: 'w1', title: 'In the Aeroplane Over the Sea', artist: 'Neutral Milk Hotel', year: 1998, genre: 'Indie Folk', format: 'vinyl', priority: 'high', targetPrice: 35, color: '#F2C66D' },
  { id: 'w2', title: 'Loveless', artist: 'My Bloody Valentine', year: 1991, genre: 'Shoegaze', format: 'vinyl', priority: 'high', targetPrice: 60, color: '#E87575' },
  { id: 'w3', title: 'Ready to Die', artist: 'The Notorious B.I.G.', year: 1994, genre: 'Hip-Hop', format: 'cd', priority: 'medium', targetPrice: 20, color: '#A69BC8' },
  { id: 'w4', title: 'Ágætis byrjun', artist: 'Sigur Rós', year: 1999, genre: 'Post-Rock', format: 'vinyl', priority: 'medium', targetPrice: 40, color: '#91C9AD' },
  { id: 'w5', title: 'Vespertine', artist: 'Björk', year: 2001, genre: 'Electronic', format: 'cassette', priority: 'low', targetPrice: 15, color: '#F4A987' },
]
